package com.sa.healntrack.billing_service.common.application.error;

public enum ErrorCode {
    INVALID_REQUEST_ID,
    EMPTY_SUBJECT,

    EMPTY_TAX_ID,
    INVALID_TAX_ID,
    EMPTY_TEMPLATE_KEY,

    EMPTY_ITEM_NAME,
    INVALID_ITEM_QTY,
    INVALID_ITEM_PRICE,
    INVALID_ITEM_SUBTOTAL,
    INCONSISTENT_ITEM_TOTAL,

    EMPTY_USER,
    EMPTY_USER_EMAIL,
    INVALID_USER_EMAIL,

    EMPTY_INVOICE_TITLE,
    EMPTY_INVOICE_DESCRIPTION,
    EMPTY_ITEMS,
    INVALID_TOTAL,
    EMPTY_DATE,

    DESERIALIZATION_ERROR,
    TEMPLATE_RENDER_ERROR,
    KAFKA_PUBLISH_ERROR,
    UNKNOWN_ERROR
}
